### ISSUE TITLE
Documentation discrepancy GET /commands

### ISSUE THREAD

**Issue by BrokenButler** [The-Microservice-Dungeon/game#113]
When succesful this returns a List<Command> not what the API says.

**Comment by BrokenButler** [comment]
Also the errors are:
201 - succesful
400 - if "future" rounds are requested
401 - if the current round is requested

**Comment by FGrueterich** [comment]
Are these changes just on your branch? Because the error-codes fit the code atm. And the api gives back and list (its just writen as an array, becausethis is the only listing possible in apis.)
