### ISSUE TITLE
Error 500 when POST /games

### ISSUE THREAD

**Issue by stefanbente** [The-Microservice-Dungeon/game#70]
Stacktrace: microservice.dungeon.game.aggregates.core.MethodNotAllowedForStatusException: RoundStarted cannot created with round.status = CREATED\n\tat microservice.dungeon.game.aggregates.game.events.GameStarted.<init>(GameStarted.kt:23)\n\tat microservice.dungeon.game.aggregates.game.events.GameStarted.<init>(GameStarted.kt:19)\n\tat microservice.dungeon.game.aggregates.game.servives.GameService.createNewGame(GameService.kt:41)

Request body: 
{
    "maxPlayers": 200,
    "maxRounds": 50
}

**Comment by atto-bit** [comment]
![grafik](https://user-images.githubusercontent.com/16986593/148051772-540c7d52-05dc-4cd6-8a35-9c0f50ae5891.png)

Neues Image ermöglicht post/games

Folgefehler entsteht: get/games issue erstellt

timestamp": "2022-01-04T11:22:07.092+00:00",
    "status": 500,
    "error": "Internal Server Error",

"message": "Null value was assigned to a property [class microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers] of primitive type setter of microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property [class microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers] of primitive type setter of microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers",
