### ISSUE TITLE
IMPLEMENTATION: POST /games creates a game with a maximum of 0 players

### ISSUE THREAD

**Issue by dadepu** [The-Microservice-Dungeon/game#88]

**Comment by daskycodes** [comment]
@dadepu 

Im `POST /games` müsste der json payload so aussehen:

```json
{
  "maxRounds": 58,
  "maxPlayers": 6
}
```

Statt wie aktuell in den docs:  https://the-microservice-dungeon.github.io/docs/openapi/game#tag/games/paths/~1games/post

```json
{
  "numberOfRounds": 58,
  "numberOfMaxPlayers": 6
}
```

Dann klappt es!
