### ISSUE TITLE
IMPLEMENTATION: game Patch

### ISSUE THREAD

**Issue by FGrueterich** [The-Microservice-Dungeon/game#94]
Patch gibt als Response eine Gameentität zurück, was eigentlich nicht gewollt ist. War das von den Admins direkt angefragt wurden und damit ein Fehler in der Doku oder einfach so dazugeschrieben? Dann bitte rausnehmen.

**Comment by atto-bit** [comment]
Fix will be implemented till the 12.1.2021 end of day

**Comment by atto-bit** [comment]
response Body was omitted. Only Status as response.
