### ISSUE TITLE
Players that join aren't actually saved in playerList

### ISSUE THREAD

**Issue by FGrueterich** [The-Microservice-Dungeon/game#95]

**Comment by BrokenButler** [comment]
Spieler scheinen nicht gespeichert zu werden, denn GET /games gibt eine leere playerList wieder.

**Comment by atto-bit** [comment]
Very quick and dirty proposal:

playerInGame aus Game entity nehmen. 
PlayersInGame als eigene Entity/Tabelle stehen lassen.(one to many beziehung auflösen)
PK auf gameId und playerId setzen -> das sollte doppelte Eintragungen verhindern.
Kurzfristig restrains wie maxPlayers aus Game würden übergangen werden, mehr Spieler als vorgesehen könnten sich anmelden (für den 14.1 sollte das erstmal kein Probem sein)
get/playersingames -> um sich die gesamte Liste Spieler+Games Zuordnungen ausgeben zu lassen
@FGrueterich please decide

**Comment by baldhat** [comment]
Why don't you save the players via a simple @ManyToMany on a Set of Players inside Game?
